apiVersion: v1
kind: Secret
metadata:
    name: dev-cluster-spec
    labels:
        argocd.argoproj.io/secret-type: cluster
    annotations:
        managed-by: argocd.argoproj.io
type: Opaque
stringData:
    name: dev-cluster
    config: ENC[AES256_GCM,data:KgwWnhpgE7kKe1HP2aguW7GliFxsSaS6uC/55h5cqS0k/3YdetB0mv5y5Iu2d9rTNW1nIB2Hk7GHp80ypzVAIYydXDpOEZb/SEzX1BCD/A==,iv:6m5rQPEzovX4TYJlGvAH0c0azgy/IKRrQ0HvGC8Ej3s=,tag:SIthVxHVhuB8tMGuXd1vHw==,type:str]
    namespaces: aicoe-argocd-dev,argocd-test
    server: https://kubernetes.default.svc
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-09-30T15:30:40Z'
    mac: ENC[AES256_GCM,data:ORUlDoPHIZl+WhyjvNHwdXUVcMwLlWBbmOw26fu2KFI8NATJooDXiglICiJvblvqngC0ImGcGizDaylN0qoBd1GBVUiJb7RJ8chy/QGjmqH2W2vn+aCIMKOu1cb7lfZazItfFJ2EEEx9s2z5IXUFRWxGCyxEmAGm3YJWzM5pMO0=,iv:SiYi4tjw0esfB2Y1272bj3QZGtUvdAvNaylfnM+Bt84=,tag:KdsMB29gNYL6klNhNYgmDQ==,type:str]
    pgp:
    -   created_at: '2020-09-04T14:04:56Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA4ewWWewNLhTAQf/Ujky/5aWwkPYvU+6w1YhRSEhG9/MRcAUt2Biu+QEjwzL
            jXoftz4Jtzi06YzGedc6w38vEfDe+JBYU8qOLZ+OYs3V6b/+wrvtJxPbsvk1ZtbZ
            7goU/oMZ2k0sWqxaxFdvRNln2es9OKK5saaCNyBvDNeBHGCn9YKW8QUP1WW6V8Io
            hlT/fVASz2HD3rGhcUNF0v6/yu9dmwpHkfCGT56ynhfaiFVwa+FVwaALS9E/eqgP
            KUaDWoG8w4uD+3Ko4CVuVUrsdPjbxsU7rWhvqIGuWTetTW4a/kvma/Njxq/mHDun
            pcWoPwZ5PNFf71gJxcnfU9ocLE6+wKt/oTd/Bm6uy9JcAYDMOwinhJYrCmROgq/Q
            ws6Bqiyp0JkV3EvfzBz5Xoc5viuHnPwo0Cjgo12nPJpIjvx1S8X3cmito686RQRx
            wFkof+S+Z2SsqJv4nFIC5vzwBa5HFtsS7TuNeGA=
            =+OkQ
            -----END PGP MESSAGE-----
        fp: CD1AFE846A21A236CEF18FF56555786B3A496099
    encrypted_regex: ^(config)$
    version: 3.6.0
